"""
Daily email alert module for stock technical analysis.

Uses Python stdlib smtplib + email to send daily alert emails
with technical analysis summaries for all watchlist stocks.

Usage:
    python -m app.alert          # run daily alert
    python -m app.alert --test   # send a test email
"""

from __future__ import annotations

import argparse
import os
import smtplib
import sys
from datetime import datetime
from email.mime.text import MIMEText
from pathlib import Path

from app.core.data_fetcher import fetch_ohlcv, get_company_name
from app.core.indicators import compute_all_indicators
from app.core.signals import generate_signal
from app.core.watchlist_store import load_watchlist


def _find_dotenv() -> Path | None:
    candidate = Path(__file__).parent.parent / ".env"
    if candidate.exists():
        return candidate
    return None


def _load_dotenv(path: Path) -> None:
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


_env_path = _find_dotenv()
if _env_path:
    _load_dotenv(_env_path)


_REQUIRED_KEYS = [
    "ALERT_EMAIL_SMTP_HOST",
    "ALERT_EMAIL_PORT",
    "ALERT_EMAIL_USER",
    "ALERT_EMAIL_PASS",
    "ALERT_EMAIL_FROM",
    "ALERT_EMAIL_TO",
]


def _get_smtp_config() -> dict[str, str]:
    """Read SMTP configuration from environment variables.

    Returns:
        dict with keys: host, port, user, password, from_addr, to_addrs

    Raises:
        SystemExit with a clear message if any required var is missing.
    """
    missing = []
    config: dict[str, str] = {}
    for key in _REQUIRED_KEYS:
        val = os.environ.get(key, "").strip()
        if not val:
            missing.append(key)
        config[key] = val

    if missing:
        print("ERROR: Missing required environment variables:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        print(file=sys.stderr)
        print(
            "Copy backend/.env.example to backend/.env and fill in the alert email section.",
            file=sys.stderr,
        )
        sys.exit(1)

    return {
        "host": config["ALERT_EMAIL_SMTP_HOST"],
        "port": int(config["ALERT_EMAIL_PORT"]),
        "user": config["ALERT_EMAIL_USER"],
        "password": config["ALERT_EMAIL_PASS"],
        "from_addr": config["ALERT_EMAIL_FROM"],
        "to_addrs": [addr.strip() for addr in config["ALERT_EMAIL_TO"].split(",")],
    }


def _build_daily_body(tickers_data: list[dict]) -> str:
    date_str = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"Stock Technical Analysis Daily Alert — {date_str}",
        "=" * 55,
        "",
    ]

    for i, td in enumerate(tickers_data, 1):
        lines.append(f"{'─' * 55}")
        lines.append(f"  #{i}  {td['ticker']}  —  {td['company']}")
        lines.append(f"{'─' * 55}")

        if td.get("error"):
            lines.append(f"  Status  : ERROR — {td['error']}")
        else:
            direction_label = {"bullish": "▲ BULLISH", "bearish": "▼ BEARISH", "neutral": "◆ NEUTRAL"}
            label = direction_label.get(td["direction"], td["direction"].upper())
            lines.append(f"  Signal      : {label}")
            lines.append(f"  Confidence  : {td['confidence']:.1f}%")
            lines.append(f"  Support     : {td['support']:.2f}")
            lines.append(f"  Resistance  : {td['resistance']:.2f}")
            if td.get("summary"):
                lines.append(f"  Summary     : {td['summary']}")
        lines.append("")

    lines.append("=" * 55)
    lines.append("Generated by Stock Predict Alert System")
    lines.append(f"Report time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    return "\n".join(lines)


def _build_test_body() -> str:
    return (
        f"Stock Predict Alert Test\n"
        f"{'=' * 30}\n\n"
        f"This is a test email from the Stock Predict alert module.\n\n"
        f"If you received this, the SMTP configuration is working correctly.\n\n"
        f"Sent at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    )


def send_email(
    *,
    host: str,
    port: int,
    user: str,
    password: str,
    from_addr: str,
    to_addrs: list[str],
    subject: str,
    body: str,
) -> None:
    """Send a plain-text email via SMTP (STARTTLS)."""
    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(to_addrs)

    try:
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(user, password)
            server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        print(f"ERROR: SMTP authentication failed — check ALERT_EMAIL_USER / ALERT_EMAIL_PASS", file=sys.stderr)
        print(f"  Details: {e}", file=sys.stderr)
        sys.exit(1)
    except (smtplib.SMTPException, OSError) as e:
        print(f"ERROR: SMTP connection failed — host={host}:{port}", file=sys.stderr)
        print(f"  Details: {e}", file=sys.stderr)
        sys.exit(1)


def send_daily_alert() -> int:
    """Load watchlist, compute signals, build + send daily alert email.

    Returns:
        0 on success, 1 if all tickers failed (but email is still sent).
    """
    config = _get_smtp_config()
    tickers = load_watchlist()

    if not tickers:
        print("Watchlist is empty. Nothing to report.", file=sys.stderr)
        return 0

    tickers_data: list[dict] = []
    failures = 0

    for ticker in tickers:
        try:
            df = fetch_ohlcv(ticker, use_cache=True)
            df = compute_all_indicators(df)
            signal = generate_signal(df, ticker=ticker)
            company = get_company_name(ticker)

            tickers_data.append({
                "ticker": ticker,
                "company": company,
                "direction": signal.direction,
                "confidence": signal.confidence,
                "support": signal.key_support,
                "resistance": signal.key_resistance,
                "summary": signal.summary,
            })
        except Exception as e:
            failures += 1
            tickers_data.append({
                "ticker": ticker,
                "company": ticker,
                "error": str(e),
            })

    body = _build_daily_body(tickers_data)
    date_str = datetime.now().strftime("%Y-%m-%d")
    subject = f"Stock Predict Daily Alert — {date_str}"

    send_email(
        host=config["host"],
        port=config["port"],
        user=config["user"],
        password=config["password"],
        from_addr=config["from_addr"],
        to_addrs=config["to_addrs"],
        subject=subject,
        body=body,
    )

    success_count = len(tickers) - failures
    print(f"Daily alert sent: {success_count}/{len(tickers)} stocks summarized, {failures} failures")
    return 0


def send_test_email() -> None:
    """Send a simple test email to verify SMTP configuration."""
    config = _get_smtp_config()
    send_email(
        host=config["host"],
        port=config["port"],
        user=config["user"],
        password=config["password"],
        from_addr=config["from_addr"],
        to_addrs=config["to_addrs"],
        subject="Stock Predict Alert Test",
        body=_build_test_body(),
    )
    print("Test email sent successfully!")
    print(f"  From: {config['from_addr']}")
    print(f"  To:   {', '.join(config['to_addrs'])}")
    print(f"  Host: {config['host']}:{config['port']}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Stock Predict daily alert email sender",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Send a test email to verify SMTP configuration",
    )
    args = parser.parse_args()

    if args.test:
        send_test_email()
    else:
        sys.exit(send_daily_alert())


if __name__ == "__main__":
    main()
